### ISSUE TITLE
你觉得angular和vue比的话，有什么优缺点？

### ISSUE THREAD

**Issue by martinwithyou** [doggy8088/angular-zero#1]
你觉得angular和vue比的话，有什么优缺点？
在台湾的前端开发中，一般用什么前端开发框架吗？
譬如vue,  echarts, weex?
这些中国本土发的框架，用的多吗？

**Comment by doggy8088** [comment]
您好：

我覺得 Angular 與 Vue 各有優缺點，網路上其實有很多評比的文章，你是可以都參考看看。

以我個人的經驗，Vue 相對簡易、好上手，用過 AngularJS 1.x 的人，要移轉到 Vue 並不難，門檻相對低。而 Angular 對我來說，語言、架構、工具整合的相當全面且完整，學習門檻也不高，後續的發展性也非常大，我覺得比較值得投資。

在台灣，如果別強調 SPA 開發框架，大多會用 Angular, React, Vue 為主，我比較少聽到有人用其他的。另外，我也比較少聽到有人用中國大陸開發的框架。

**Comment by martinwithyou** [comment]
echarts 是百度的数据可视化框架，今年全票通过阿帕奇基金会，
weex, 是阿里巴巴的混合开发框架，用js来开发android, ios 应用的。

**Comment by martinwithyou** [comment]
但是angular 在我们这边互联网公司里面，其实用的很少啊，大多是传统的制造业的业务系统用的比较多

**Comment by doggy8088** [comment]
我看到大型互聯網公司的確比較少用 Angular 框架，這套框架還是比較適合給一般企業使用。
