### ISSUE TITLE
还有，你这边有什么好的台湾的前端项目可以介绍一下吗？ 我可以和我们的朋友们分享。

### ISSUE THREAD

**Issue by martinwithyou** [doggy8088/angular-zero#2]
还有，你这边有什么好的台湾的前端项目可以介绍一下吗？
 我可以和我们的朋友们分享。
谢谢。
我也希望你们也可以多多关注一下我们大陆的前端框架，
我们这边的互联网行业也是除了美国之外，发展的不错的地方。
可以多多交流。

**Comment by doggy8088** [comment]
老實說，台灣前端項目好像不多。

**Comment by martinwithyou** [comment]
我在手机邮件里面看到您的二维码了，但是不知道为什么在电脑上看不到。好奇怪。

**Comment by doggy8088** [comment]
我故意刪掉的，不想這麼多人加我微信！ 😃
